const CACHE_NAME = 'wargame-v13.001';

const ASSETS = [
      // ====== КОРНЕВЫЕ ФАЙЛЫ ======
    './',
    './index.html',
    './css/style.css',
    './js/data.js',
    './js/weapons.js',
    './js/cards.js',
    './js/templates.js',
    './manifest.json',

    // ====== ОБЩИЕ ИЗОБРАЖЕНИЯ (images/) ======
    './images/Hotchkis.png',
    './images/Star Si-35.png',
    './images/Vz.24.png',
    './images/Zb.26.png',
    './images/commisar AIRF.png',
    './images/Аварийный тормоз.png',
    './images/Ампуломет.png',
    './images/Бельгийское упрямтсво.png',
    './images/Бутылкомет.png',
    './images/Бюрократия.png',
    './images/Велоблиц.png',
    './images/Горное пончо.png',
    './images/Горные охотники.png',
    './images/Дисковый магазин к FN model D.png',
    './images/Длинное дыхание.png',
    './images/За республику.png',
    './images/Знак колониальной службы.png',
    './images/ИПП БеВе.png',
    './images/ИПП аирф.png',
    './images/Кальвинистская сдержанность.png',
    './images/Кальвинистская эффективность.png',
    './images/Клинок риспублики.png',
    './images/Марадерство.png',
    './images/Нашивка за ранение АИРФ.png',
    './images/Нестабильные гранаты.png',
    './images/Но пасаран.png',
    './images/Орден преданности республике.png',
    './images/Плохой порох.png',
    './images/РОКС-3.png',
    './images/Снайперская винтовка.jpg',
    './images/Снайперская винтовка.png',
    './images/Торговый дух.png',
    './images/Усиленный паек Беве.png',
    './images/Фламандская фурия.png',
    './images/Хрупкая оптика.png',
    './images/Хуэлга.png',
    './images/Шахтерский динамит.png',
    './images/Языковой барьер.png',
    './images/анархисты.png',
    './images/бат аирф.png',
    './images/болото 1.png',
    './images/болото 2.png',
    './images/бтр1.jpg',
    './images/бтр2.jpg',
    './images/бтр3.jpg',
    './images/бутылки с зажигательной смесью.png',
    './images/велосипедная стоянка.png',
    './images/горный туризм.png',
    './images/дорога развилка.png',
    './images/дорога.png',
    './images/дорога1.png',
    './images/дымы.png',
    './images/знаг заслуг бенелюкс.png',
    './images/знак за ближний бой Беве.png',
    './images/знак интербригады.png',
    './images/интербригада.png',
    './images/кальвинистская бережливость.png',
    './images/камни.png',
    './images/камни1.png',
    './images/камни2.png',
    './images/кумулятивная граната.png',
    './images/кусты.png',
    './images/кусты1.png',
    './images/кусты2.png',
    './images/лес.png',
    './images/лес1.png',
    './images/лес2.png',
    './images/медаль леопольда.png',
    './images/мин аирф 82.png',
    './images/ни шагу назад бельгийцы.png',
    './images/ночь.png',
    './images/огненное поле аирф.png',
    './images/окоп1.png',
    './images/окоп2.png',
    './images/окоп3.png',
    './images/окоп4.png',
    './images/окоп5.png',
    './images/окоп6.png',
    './images/орден солнца.png',
    './images/оружие солидарности.png',
    './images/ослепляющая граната.png',
    './images/паек аирф.png',
    './images/пистолет Star.png',
    './images/пто2.jpg',
    './images/пуль1.jpg',
    './images/развед аирф.png',
    './images/рота аирф 1.png',
    './images/рота аирф 2.png',
    './images/рота аирф 3.png',
    './images/санитары беве.png',
    './images/сапер1.jpg',
    './images/сапер2.jpg',
    './images/сапер3.jpg',
    './images/саперная доблесть.png',
    './images/склон1.png',
    './images/склон2.png',
    './images/склон3.png',
    './images/склон4.png',
    './images/склон5.png',
    './images/склон6.png',
    './images/склон7.png',
    './images/склон8.png',
    './images/склон9.png',
    './images/склон10.png',
    './images/склон11.png',
    './images/склон12.png',
    './images/склон13.png',
    './images/склон14.png',
    './images/собачья упряжка.jpg',
    './images/стрел 1.jpg',
    './images/стрел 2.jpg',
    './images/стрелковый взвод аирф №1.png',
    './images/стрелковый взвод аирф №2.png',
    './images/стрелковый взвод аирф №4.png',
    './images/стрелковый взвод аирф №5.png',
    './images/стрелковый взвод аирф №7.png',
    './images/стрелковый взвод аирф №8.png',
    './images/талреп-якорь.png',
    './images/термитный заряд.png',
    './images/трава.png',
    './images/трава1.png',
    './images/устаревшие патроны.png',
    './images/фосфорная граната аирф.png',
    './images/шеврон беве за ранение.png',
    './images/штаб1 саперский.png',
    './images/штаб1.jpg',
    './images/штурм 1.jpg',
    './images/штурм 2.jpg',
    './images/штурмовой взвод аирф №3.png',
    './images/штурмовой взвод аирф №6.png',
    './images/штурмовой взвод аирф №9.png',

    // ====== AIRF (images/AIRF/) ======
    './images/AIRF/AIRF.png',
    './images/AIRF/БТР аирф Llanero группа из 2.png',
    './images/AIRF/БТР аирф Llanero группа из 3.png',
    './images/AIRF/БТР аирф Llanero группа из 4.png',
    './images/AIRF/БТР аирф Llanero группа из 5.png',
    './images/AIRF/бтр4.png',
    './images/AIRF/бтр5.png',
    './images/AIRF/лт аирф CL39 группа из 2.png',
    './images/AIRF/лт аирф CL39 группа из 3.png',
    './images/AIRF/лт аирф CL39 группа из 4.png',
    './images/AIRF/лт аирф CL39 группа из 5.png',
    './images/AIRF/лт аирф CL39 №1.png',
    './images/AIRF/лт аирф CL39 №2.png',
    './images/AIRF/лт аирф CL39 №3.png',
    './images/AIRF/лт аирф CL39 №4.png',
    './images/AIRF/лт аирф CL39 №5.png',
    './images/AIRF/развед аирф 1.png',
    './images/AIRF/развед аирф 2.png',
    './images/AIRF/рота аирф 1.png',
    './images/AIRF/рота аирф 2.png',
    './images/AIRF/рота аирф 3.png',

    // ====== BeVe (images/BeVe/) ======
    './images/BeVe/BeVe.png',
    './images/BeVe/Belgian Beve.png',
    './images/BeVe/Fn24.png',
    './images/BeVe/Geweer m95.png',
    './images/BeVe/Landsverk 183 группа из 2.png',
    './images/BeVe/Landsverk 183 группа из 3.png',
    './images/BeVe/OIP.png',
    './images/BeVe/Schwarcloze.png',
    './images/BeVe/fn d exp.png',
    './images/BeVe/fn md.png',
    './images/BeVe/johnson41.png',
    './images/BeVe/БА Landsverk 183 №1.jpg',
    './images/BeVe/БА Landsverk 183 №2.jpg',
    './images/BeVe/БА Landsverk 183 №3.jpg',
    './images/BeVe/ДОТ Bosh.png',
    './images/BeVe/САУ Brugge группа из 2.png',
    './images/BeVe/САУ Brugge группа из 3.png',
    './images/BeVe/САУ Brugge №1.jpg',
    './images/BeVe/САУ Brugge №2.jpg',
    './images/BeVe/САУ Brugge №3.jpg',
    './images/BeVe/браунинг хай пауэр.png',
    './images/BeVe/велостоянка метка.png',
    './images/BeVe/влосипедисты 1.png',
    './images/BeVe/влосипедисты 2.png',
    './images/BeVe/влосипедисты 3.png',
    './images/BeVe/влосипедисты 4.png',
    './images/BeVe/влосипедисты 5.png',
    './images/BeVe/влосипедисты 6.png',
    './images/BeVe/влосипедисты 7.png',
    './images/BeVe/влосипедисты 8.png',
    './images/BeVe/влосипедисты 9.png',
    './images/BeVe/влосипедисты 10.png',
    './images/BeVe/влосипедисты 11.png',
    './images/BeVe/влосипедисты 12.png',
    './images/BeVe/влосипедисты поддержка 1.png',
    './images/BeVe/влосипедисты поддержка 2.png',
    './images/BeVe/влосипедисты поддержка 3.png',
    './images/BeVe/горящее поле.png',
    './images/BeVe/мина 82 1.jpg',
    './images/BeVe/мина 82 2.jpg',
    './images/BeVe/мина 82 3.jpg',
    './images/BeVe/мотоцикл беве 1.jpg',
    './images/BeVe/мотоцикл беве 2.jpg',
    './images/BeVe/мотоцикл беве 3.jpg',
    './images/BeVe/отделение бе1 бельг.jpg',
    './images/BeVe/отделение бе1.jpg',
    './images/BeVe/отделение бе2 бельг.jpg',
    './images/BeVe/отделение бе2.jpg',
    './images/BeVe/отделение бе3 бельг.jpg',
    './images/BeVe/отделение бе3.jpg',
    './images/BeVe/отделение бе4 бельг.jpg',
    './images/BeVe/отделение бе4.jpg',
    './images/BeVe/отделение бе5 бельг.jpg',
    './images/BeVe/отделение бе5.jpg',
    './images/BeVe/отделение бе6 бельг.jpg',
    './images/BeVe/отделение бе6.jpg',
    './images/BeVe/отделение бе7 бельг.jpg',
    './images/BeVe/отделение бе7.jpg',
    './images/BeVe/отделение бе8 бельг.jpg',
    './images/BeVe/отделение бе8.jpg',
    './images/BeVe/отделение бе9 бельг.jpg',
    './images/BeVe/отделение бе9.jpg',
    './images/BeVe/отделение под1 бель.jpg',
    './images/BeVe/отделение под1.jpg',
    './images/BeVe/отделение под2 бель.jpg',
    './images/BeVe/отделение под2.jpg',
    './images/BeVe/отделение под3 бель.jpg',
    './images/BeVe/отделение под3.jpg',
    './images/BeVe/отделение пуль1.jpg',
    './images/BeVe/отделение пуль2.jpg',
    './images/BeVe/отделение пуль3.jpg',
    './images/BeVe/отделение пуль4.jpg',
    './images/BeVe/отделение пуль5.jpg',
    './images/BeVe/отделение пуль6.jpg',
    './images/BeVe/пто.jpg',
    './images/BeVe/пто2.jpg',
    './images/BeVe/снайпер Беве 1.png',
    './images/BeVe/снайпер беве 1.jpg',
    './images/BeVe/снайпер беве 2.jpg',
    './images/BeVe/снайпер беве 3.jpg',
    './images/BeVe/штаб батальона BeVe.jpg',
    './images/BeVe/штаб бел вззод 2.jpg',
    './images/BeVe/штаб бел вззод 3.jpg',
    './images/BeVe/штаб бел.jpg',
    './images/BeVe/штаб гол взв 2.jpg',
    './images/BeVe/штаб гол взв 3.jpg',
    './images/BeVe/штаб гол.jpg',
    './images/BeVe/штаб мин.jpg',
    './images/BeVe/штаб мин2.jpg',
    './images/BeVe/штаб мин3.jpg',
    './images/BeVe/штаб мин4.jpg',
    './images/BeVe/штаб мин5.jpg',
    './images/BeVe/штаб мин6.jpg',
    './images/BeVe/штаб роты BeVe гол.jpg',
    './images/BeVe/штаб роты BeVe бел.jpg',
    './images/BeVe/штаб роты BeVe сам.jpg',
    './images/BeVe/штаб самокат вззод 1.jpg',
    './images/BeVe/штаб самокат вззод 2.jpg',
    './images/BeVe/штаб самокат вззод 3.jpg',

    // ====== КАРТЫ ======
    './maps/Валенсия.png',
    './maps/valencia_terrain.json',
    './maps/index.json',
  
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS);
    })
  );
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});
