// ⚡ v13.024: имя кэша обязательно обновлять с каждой версией —
//    иначе старый (устаревший) кэш продолжает отдавать старые js/data.js
const CACHE_NAME = 'wargame-v13.050';

const ASSETS = [
      // ====== КОРНЕВЫЕ ФАЙЛЫ ======
    './',
    './index.html',
    './css/style.css',
    './js/data.js',
    './js/weapons.js',
    './js/cards.js',
    './js/templates.js',
    './manifest.json',

    // ====== ОБЩИЕ ИЗОБРАЖЕНИЯ (images/) ======
    './images/Hotchkis.png',
    './images/Star Si-35.png',
    './images/Vz.24.png',
    './images/Zb.26.png',
    './images/commisar AIRF.png',
    './images/Аварийный тормоз.png',
    './images/Скоординированный заградительный огонь.png',
    './images/Залп отчаяния.png',
    './images/Ампуломет.png',
    './images/Бельгийское упрямтсво.png',
    './images/Бутылкомет.png',
    './images/Бюрократия.png',
    './images/Велоблиц.png',
    './images/Горное пончо.png',
    './images/Горные охотники.png',
    './images/Дисковый магазин к FN model D.png',
    './images/Длинное дыхание.png',
    './images/За республику.png',
    './images/Знак колониальной службы.png',
    './images/ИПП БеВе.png',
    './images/ИПП аирф.png',
    './images/Кальвинистская сдержанность.png',
    './images/Кальвинистская эффективность.png',
    './images/Клинок риспублики.png',
    './images/Марадерство.png',
    './images/Нашивка за ранение АИРФ.png',
    './images/Нестабильные гранаты.png',
    './images/Но пасаран.png',
    './images/Орден преданности республике.png',
    './images/Плохой порох.png',
    './images/РОКС-3.png',
    './images/Снайперская винтовка.jpg',
    './images/Снайперская винтовка.png',
    './images/Торговый дух.png',
    './images/Усиленный паек Беве.png',
    './images/Фламандская фурия.png',
    './images/Хрупкая оптика.png',
    './images/Хуэлга.png',
    './images/Шахтерский динамит.png',
    './images/Языковой барьер.png',
    './images/анархисты.png',
    './images/бат аирф.png',
    './images/болото 1.png',
    './images/болото 2.png',
    './images/bonuses/fire_control.png',
    './images/bonuses/radio_phillips.png',
    './images/bonuses/motor_courier.png',
    './images/bonuses/siesta.png',
    './images/bonuses/chaskeys.png',
    './images/бтр1.jpg',
    './images/бтр2.jpg',
    './images/бтр3.jpg',
    './images/бутылки с зажигательной смесью.png',
    './images/велосипедная стоянка.png',
    './images/горный туризм.png',
    './images/дорога развилка.png',
    './images/дорога.png',
    './images/дорога1.png',
    './images/дымы.png',
    './images/знаг заслуг бенелюкс.png',
    './images/знак за ближний бой Беве.png',
    './images/знак интербригады.png',
    './images/интербригада.png',
    './images/кальвинистская бережливость.png',
    './images/камни.png',
    './images/камни1.png',
    './images/камни2.png',
    './images/кумулятивная граната.png',
    './images/кусты.png',
    './images/кусты1.png',
    './images/кусты2.png',
    './images/лес.png',
    './images/лес1.png',
    './images/лес2.png',
    './images/медаль леопольда.png',
    './images/мин аирф 82.png',
    './images/ни шагу назад бельгийцы.png',
    './images/ночь.png',
    './images/огненное поле аирф.png',
    './images/окоп1.png',
    './images/окоп2.png',
    './images/окоп3.png',
    './images/окоп4.png',
    './images/окоп5.png',
    './images/окоп6.png',
    './images/орден солнца.png',
    './images/оружие солидарности.png',
    './images/ослепляющая граната.png',
    './images/паек аирф.png',
    './images/пистолет Star.png',
    './images/пто2.jpg',
    './images/пуль1.jpg',
    './images/развед аирф.png',
    './images/рота аирф 1.png',
    './images/рота аирф 2.png',
    './images/рота аирф 3.png',
    './images/санитары беве.png',
    './images/сапер1.jpg',
    './images/сапер2.jpg',
    './images/сапер3.jpg',
    './images/саперная доблесть.png',
    './images/склон1.png',
    './images/склон2.png',
    './images/склон3.png',
    './images/склон4.png',
    './images/склон5.png',
    './images/склон6.png',
    './images/склон7.png',
    './images/склон8.png',
    './images/склон9.png',
    './images/склон10.png',
    './images/склон11.png',
    './images/склон12.png',
    './images/склон13.png',
    './images/склон14.png',
    './images/собачья упряжка.jpg',
    './images/стрел 1.jpg',
    './images/стрел 2.jpg',
    './images/стрелковый взвод аирф №1.png',
    './images/стрелковый взвод аирф №2.png',
    './images/стрелковый взвод аирф №4.png',
    './images/стрелковый взвод аирф №5.png',
    './images/стрелковый взвод аирф №7.png',
    './images/стрелковый взвод аирф №8.png',
    './images/талреп-якорь.png',
    './images/термитный заряд.png',
    './images/трава.png',
    './images/трава1.png',
    './images/устаревшие патроны.png',
    './images/фосфорная граната аирф.png',
    './images/шеврон беве за ранение.png',
    './images/штаб1 саперский.png',
    './images/штаб1.jpg',
    './images/штурм 1.jpg',
    './images/штурм 2.jpg',
    './images/штурмовой взвод аирф №3.png',
    './images/штурмовой взвод аирф №6.png',
    './images/штурмовой взвод аирф №9.png',

    // ====== AIRF (images/AIRF/) ======
    './images/AIRF/AIRF.png',
    './images/AIRF/БТР аирф Llanero группа из 2.png',
    './images/AIRF/БТР аирф Llanero группа из 3.png',
    './images/AIRF/БТР аирф Llanero группа из 4.png',
    './images/AIRF/БТР аирф Llanero группа из 5.png',
    './images/AIRF/бтр4.png',
    './images/AIRF/бтр5.png',
    './images/AIRF/лт аирф CL39 группа из 2.png',
    './images/AIRF/лт аирф CL39 группа из 3.png',
    './images/AIRF/лт аирф CL39 группа из 4.png',
    './images/AIRF/лт аирф CL39 группа из 5.png',
    './images/AIRF/лт аирф CL39 №1.png',
    './images/AIRF/лт аирф CL39 №2.png',
    './images/AIRF/лт аирф CL39 №3.png',
    './images/AIRF/лт аирф CL39 №4.png',
    './images/AIRF/лт аирф CL39 №5.png',
    './images/AIRF/развед аирф 1.png',
    './images/AIRF/развед аирф 2.png',
    './images/AIRF/рота аирф 1.png',
    './images/AIRF/рота аирф 2.png',
    './images/AIRF/рота аирф 3.png',

    // ====== BeVe (images/BeVe/) ======
    './images/BeVe/BeVe.png',
    './images/BeVe/Belgian Beve.png',
    './images/BeVe/Fn24.png',
    './images/BeVe/Geweer m95.png',
    './images/BeVe/Landsverk 183 группа из 2.png',
    './images/BeVe/Landsverk 183 группа из 3.png',
    './images/BeVe/OIP.png',
    './images/BeVe/Schwarcloze.png',
    './images/BeVe/fn d exp.png',
    './images/BeVe/fn md.png',
    './images/BeVe/johnson41.png',
    './images/BeVe/БА Landsverk 183 №1.jpg',
    './images/BeVe/БА Landsverk 183 №2.jpg',
    './images/BeVe/БА Landsverk 183 №3.jpg',
    './images/BeVe/ДОТ Bosh.png',
    './images/BeVe/САУ Brugge группа из 2.png',
    './images/BeVe/САУ Brugge группа из 3.png',
    './images/BeVe/САУ Brugge №1.jpg',
    './images/BeVe/САУ Brugge №2.jpg',
    './images/BeVe/САУ Brugge №3.jpg',
    './images/BeVe/браунинг хай пауэр.png',
    './images/BeVe/велостоянка метка.png',
    './images/BeVe/влосипедисты 1.png',
    './images/BeVe/влосипедисты 2.png',
    './images/BeVe/влосипедисты 3.png',
    './images/BeVe/влосипедисты 4.png',
    './images/BeVe/влосипедисты 5.png',
    './images/BeVe/влосипедисты 6.png',
    './images/BeVe/влосипедисты 7.png',
    './images/BeVe/влосипедисты 8.png',
    './images/BeVe/влосипедисты 9.png',
    './images/BeVe/влосипедисты 10.png',
    './images/BeVe/влосипедисты 11.png',
    './images/BeVe/влосипедисты 12.png',
    './images/BeVe/влосипедисты поддержка 1.png',
    './images/BeVe/влосипедисты поддержка 2.png',
    './images/BeVe/влосипедисты поддержка 3.png',
    './images/BeVe/горящее поле.png',
    './images/BeVe/мина 82 1.jpg',
    './images/BeVe/мина 82 2.jpg',
    './images/BeVe/мина 82 3.jpg',
    './images/BeVe/мотоцикл беве 1.jpg',
    './images/BeVe/мотоцикл беве 2.jpg',
    './images/BeVe/мотоцикл беве 3.jpg',
    './images/BeVe/отделение бе1 бельг.jpg',
    './images/BeVe/отделение бе1.jpg',
    './images/BeVe/отделение бе2 бельг.jpg',
    './images/BeVe/отделение бе2.jpg',
    './images/BeVe/отделение бе3 бельг.jpg',
    './images/BeVe/отделение бе3.jpg',
    './images/BeVe/отделение бе4 бельг.jpg',
    './images/BeVe/отделение бе4.jpg',
    './images/BeVe/отделение бе5 бельг.jpg',
    './images/BeVe/отделение бе5.jpg',
    './images/BeVe/отделение бе6 бельг.jpg',
    './images/BeVe/отделение бе6.jpg',
    './images/BeVe/отделение бе7 бельг.jpg',
    './images/BeVe/отделение бе7.jpg',
    './images/BeVe/отделение бе8 бельг.jpg',
    './images/BeVe/отделение бе8.jpg',
    './images/BeVe/отделение бе9 бельг.jpg',
    './images/BeVe/отделение бе9.jpg',
    './images/BeVe/отделение под1 бель.jpg',
    './images/BeVe/отделение под1.jpg',
    './images/BeVe/отделение под2 бель.jpg',
    './images/BeVe/отделение под2.jpg',
    './images/BeVe/отделение под3 бель.jpg',
    './images/BeVe/отделение под3.jpg',
    './images/BeVe/отделение пуль1.jpg',
    './images/BeVe/отделение пуль2.jpg',
    './images/BeVe/отделение пуль3.jpg',
    './images/BeVe/отделение пуль4.jpg',
    './images/BeVe/отделение пуль5.jpg',
    './images/BeVe/отделение пуль6.jpg',
    './images/BeVe/пто.jpg',
    './images/BeVe/пто2.jpg',
    './images/BeVe/снайпер Беве 1.png',
    './images/BeVe/снайпер беве 1.jpg',
    './images/BeVe/снайпер беве 2.jpg',
    './images/BeVe/снайпер беве 3.jpg',
    './images/BeVe/штаб батальона BeVe.jpg',
    './images/BeVe/штаб бел вззод 2.jpg',
    './images/BeVe/штаб бел вззод 3.jpg',
    './images/BeVe/штаб бел.jpg',
    './images/BeVe/штаб гол взв 2.jpg',
    './images/BeVe/штаб гол взв 3.jpg',
    './images/BeVe/штаб гол.jpg',
    './images/BeVe/штаб мин.jpg',
    './images/BeVe/штаб мин2.jpg',
    './images/BeVe/штаб мин3.jpg',
    './images/BeVe/штаб мин4.jpg',
    './images/BeVe/штаб мин5.jpg',
    './images/BeVe/штаб мин6.jpg',
    './images/BeVe/штаб роты BeVe гол.jpg',
    './images/BeVe/штаб роты BeVe бел.jpg',
    './images/BeVe/штаб роты BeVe сам.jpg',
    './images/BeVe/штаб самокат вззод 1.jpg',
    './images/BeVe/штаб самокат вззод 2.jpg',
    './images/BeVe/штаб самокат вззод 3.jpg',

    // ====== КАРТЫ ======
    './maps/Валенсия.png',
    './maps/valencia_terrain.json',
    './maps/index.json',
    './maps/0.11 дорога, поле, рожь.json',
 './maps/0.12 поле.json',
 './maps/0.13 поле.json',
 './maps/0.2 поле.json',
 './maps/0.3 поле.json',
 './maps/0.4 поле.json',
 './maps/0.5 поле.json',
 './maps/0.6 поле.json',
 './maps/0.7 поле.json',
 './maps/0.8 лес, поле.json',
 './maps/0.9 лес, поле.json',
 './maps/1.0 лес.json',
 './maps/1.1 лес, поле.json',
 './maps/1.10 поле, лес.json',
 './maps/1.11 дорога, поле.json',
 './maps/1.12 поле.json',
 './maps/1.13 лес, поле.json',
 './maps/1.2 поле.json',
 './maps/1.3 лес, поле.json',
 './maps/1.4 поле.json',
 './maps/1.5 поле.json',
 './maps/1.6 поле.json',
 './maps/1.7 поле.json',
 './maps/1.8 лес, поле.json',
 './maps/1.9 лес, поле.json',
 './maps/10.11 лес, болото.json',
 './maps/10.12 лес, гора.json',
 './maps/10.13 лес, гора.json',
 './maps/10.4 поле.json',
 './maps/10.5 болото, вода, поле.json',
 './maps/10.6 поле, дорога, болото, лес.json',
 './maps/10.7 лес, дорога, поле, болото.json',
 './maps/10.8 дорога, болото,поле.json',
 './maps/11.11 лес.json',
 './maps/11.12 лес, гора.json',
 './maps/11.13 лес, гора.json',
 './maps/11.7 болото.json',
 './maps/11.8 перекресток.json',
 './maps/11.9 болото.json',
 './maps/2.0 поле.json',
 './maps/2.1 лес, поле.json',
 './maps/2.10 дорога, поле. лес.json',
 './maps/2.11 лес, поле.json',
 './maps/2.12 лес, поле.json',
 './maps/2.13 лес, поле.json',
 './maps/2.2 лес поле.json',
 './maps/2.3 лес.json',
 './maps/2.4 лес.json',
 './maps/2.5 горы, кусты.json',
 './maps/2.6 поле.json',
 './maps/2.7 горы.json',
 './maps/2.8 поле, горы.json',
 './maps/2.9 поле.json',
 './maps/3.0 поле.json',
 './maps/3.1 лес, поле.json',
 './maps/3.10 дорога, поле, лес.json',
 './maps/3.11 поле, рожь.json',
 './maps/3.12 поле.json',
 './maps/3.13 лес.json',
 './maps/3.2 гора лес.json',
 './maps/3.3 горы, траншеи.json',
 './maps/3.4 лес, горы.json',
 './maps/3.5 горы.json',
 './maps/3.6 горы.json',
 './maps/3.7 горы.json',
 './maps/3.8 поле, горы, кусты.json',
 './maps/3.9 поле.json',
 './maps/4.0 поле.json',
 './maps/4.1 поле.json',
 './maps/4.10 дорога, поле.json',
 './maps/4.11 поле, гора, кусты.json',
 './maps/4.12 поле.json',
 './maps/4.13 лес.json',
 './maps/4.2 лес, гора.json',
 './maps/4.3 горы.json',
 './maps/4.4 горы, лес.json',
 './maps/4.5 горы.json',
 './maps/4.6 горы, кусты.json',
 './maps/4.7 горы.json',
 './maps/4.8 горы.json',
 './maps/4.9 поле.json',
 './maps/5.0 поле.json',
 './maps/5.1 гора.json',
 './maps/5.10 дорога, поле, лес.json',
 './maps/5.11 гора, поле.json',
 './maps/5.12 горы, поле.json',
 './maps/5.13 лес.json',
 './maps/5.2 гора.json',
 './maps/5.3 гора.json',
 './maps/5.4 гора, лес.json',
 './maps/5.5 горы, поле.json',
 './maps/5.6 горы.json',
 './maps/5.7 горы, поле.json',
 './maps/5.8 горы, поле.json',
 './maps/5.9 дорога, лес, поле.json',
 './maps/6.0 гора,поле.json',
 './maps/6.1 гора дорога.json',
 './maps/6.10 поле.json',
 './maps/6.12 лес, поле.json',
 './maps/6.13 лес.json',
 './maps/6.2 гора.json',
 './maps/6.3 гора, кусты.json',
 './maps/6.4 горы, поле.json',
 './maps/6.5 поле.json',
 './maps/6.6 горы, поле.json',
 './maps/6.7 поле, кусты.json',
 './maps/6.7 поле, рожь.json',
 './maps/6.8 поле.json',
 './maps/6.9 дорога, поле.json',
 './maps/7.0 дорога, поле, рожь.json',
 './maps/7.1 поле, рожь.json',
 './maps/7.10 болото, поле.json',
 './maps/7.12 поле, лес, болото.json',
 './maps/7.13 лес.json',
 './maps/7.2 гора дорога.json',
 './maps/7.3 гора, дорога.json',
 './maps/7.4 поле, рожь.json',
 './maps/7.5 поле, рожь.json',
 './maps/7.6 поле.json',
 './maps/7.7 поле.json',
 './maps/7.8 лес, поле.json',
 './maps/7.9 дорога, поле, лес.json',
 './maps/8.0 поле, рожь.json',
 './maps/8.1 поле, рожь.json',
 './maps/8.10 холм-болото.json',
 './maps/8.11 лес, поле, болото, холм.json',
 './maps/8.12 лес, болото.json',
 './maps/8.13 лес, гора.json',
 './maps/8.2 поле, рожь.json',
 './maps/8.3 дорога, поле, рожь.json',
 './maps/8.4 поле, рожь.json',
 './maps/8.5 поле, рожь.json',
 './maps/8.6 поле, рожь.json',
 './maps/8.7 поле, рожь.json',
 './maps/8.8 лес-дорога.json',
 './maps/8.9 дорога, горя, болото.json',
 './maps/9.12 лес.json',
 './maps/9.13 лес, гора.json',
 './maps/9.2 поле, рожь.json',
 './maps/9.3 поле.json',
 './maps/9.4 поле-дорога.json',
 './maps/9.5 поле-дорога.json',
 './maps/9.6 поле, рожь.json',
 './maps/9.7 поле, лес.json',
 './maps/9.8 дорога, болото,поле.json',
 './maps/9.9 болото.json',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS);
    })
  );
  // ⚡ v13.024: новый SW перехватывает управление сразу,
  //    не дожидаясь закрытия всех вкладок (иначе старые файлы
  //    продолжали отдаваться старым SW)
  if ('skipWaiting' in self) self.skipWaiting();
});

// ⚡ v13.024: при активации удаляем ВСЕ старые кэши.
//    Критично: caches.match() ищет по ВСЕМ кэшам, поэтому без этой
//    очистки даже с новым именем кэша отдавались бы старые файлы
//    из старого кэша (корневая причина «старого» data.js на устройствах).
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      )
    ).then(() => {
      if ('clients' in self) return self.clients.claim();
    })
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    // ⚡ v13.024: ищем ответ ТОЛЬКО в текущем кэше (caches.open(CACHE_NAME)),
    //    а не во всех кэшах (caches.match)
    caches.open(CACHE_NAME).then((cache) =>
      cache.match(event.request).then((cached) => {
        if (cached) return cached;
        return fetch(event.request).then((response) => {
          // обновляем кэш свежей версией из сети (если доступна)
          if (response && response.status === 200 && response.type === 'basic') {
            cache.put(event.request, response.clone());
          }
          return response;
        });
      })
    )
  );
});
