const CACHE_NAME = 'wargame-v12.46';

const ASSETS = [
  '/index.html',
  '/manifest.json',
  '/images/AIRF.png',
  '/images/BeVe.png',
  '/images/Belgian Beve.png',
  '/images/Fn24.png',
  '/images/Geweer m95.png',
  '/images/Hotchkis.png',
  '/images/OIP.png',
  '/images/Schwarcloze.png',
  '/images/Star Si-35.png',
  '/images/Vz.24.png',
  '/images/Zb.26.png',
  '/images/commisar AIRF.png',
  '/images/fn d exp.png',
  '/images/fn md.png',
  '/images/johnson41.png',
  '/images/Аварийный тормоз.png',
  '/images/Ампуломет.png',
  '/images/Бегун часки.png',
  '/images/Бельгийское упрямтсво.png',
  '/images/Бутылкомет.png',
  '/images/Бюрократия.png',
  '/images/Велоблиц.png',
  '/images/Водная линия.png',
  '/images/Горное пончо.png',
  '/images/Горные охотники.png',
  '/images/ДОТ Bosh.png',
  '/images/Дисковый магазин к FN model D.png',
  '/images/Длинное дыхание.png',
  '/images/За республику.png',
  '/images/Знак колониальной службы.png',
  '/images/ИПП БеВе.png',
  '/images/ИПП аирф.png',
  '/images/Кальвинистская сдержанность.png',
  '/images/Кальвинистская эффективность.png',
  '/images/Клинок риспублики.png',
  '/images/Марадерство.png',
  '/images/Нашивка за ранение АИРФ.png',
  '/images/Нестабильные гранаты.png',
  '/images/Но пасаран.png',
  '/images/Орден преданности республике.png',
  '/images/Плохой порох.png',
  '/images/РОКС-3.png',
  '/images/Снайперская винтовка.jpg',
  '/images/Торговый дух.png',
  '/images/Усиленный паек Беве.png',
  '/images/Фламандская фурия.png',
  '/images/Хрупкая оптика.png',
  '/images/Хуэлга.png',
  '/images/Шахтерский динамит.png',
  '/images/Языковой барьер.png',
  '/images/анархисты.png',
  '/images/браунинг хай пауэр.png',
  '/images/бтр1.jpg',
  '/images/бтр2.jpg',
  '/images/бтр3.jpg',
  '/images/бутылки с зажигательной смесью.png',
  '/images/велосипедная стоянка.png',
  '/images/горный стрелок.png',
  '/images/горный туризм.png',
  '/images/дорога.png',
  '/images/дорога1.png',
  '/images/дымы.png',
  '/images/знаг заслуг бенелюкс.png',
  '/images/знак за ближний бой Беве.png',
  '/images/знак интербригады.png',
  '/images/интербригада.png',
  '/images/кальвинистская бережливость.png',
  '/images/камни.png',
  '/images/камни1.png',
  '/images/камни2.png',
  '/images/корона.jpg',
  '/images/кумулятивная граната.png',
  '/images/кусты.png',
  '/images/кусты1.png',
  '/images/кусты2.png',
  '/images/лес.png',
  '/images/лес1.png',
  '/images/лес2.png',
  '/images/медаль леопольда.png',
  '/images/ни шагу назад бельгийцы.png',
  '/images/ночь.png',
  '/images/огненное поле аирф.png',
  '/images/окоп1.png',
  '/images/окоп2.png',
  '/images/окоп3.png',
  '/images/окоп4.png',
  '/images/окоп5.png',
  '/images/окоп6.png',
  '/images/орден солнца.png',
  '/images/оружие солидарности.png',
  '/images/ослепляющая граната.png',
  '/images/отделение бе1.jpg',
  '/images/отделение бе2.jpg',
  '/images/отделение бе3.jpg',
  '/images/отделение под1.jpg',
  '/images/отделение пуль1.jpg',
  '/images/паек аирф.png',
  '/images/пачамама.png',
  '/images/пистолет Star.png',
  '/images/пто.jpg',
  '/images/пуль1.jpg',
  '/images/санитары беве.png',
  '/images/сапер1.jpg',
  '/images/сапер2.jpg',
  '/images/сапер3.jpg',
  '/images/саперная доблесть.png',
  '/images/склон1.png',
  '/images/склон2.png',
  '/images/склон3.png',
  '/images/склон4.png',
  '/images/склон5.png',
  '/images/склон6.png',
  '/images/склон7.png',
  '/images/склон8.png',
  '/images/склон9.png',
  '/images/склон10.png',
  '/images/склон11.png',
  '/images/склон12.png',
  '/images/склон13.png',
  '/images/склон14.png',
  '/images/снайпер Беве 1.png',
  '/images/снайперы БЕве.png',
  '/images/собачья упряжка.jpg',
  '/images/стрел 1.jpg',
  '/images/стрел 2.jpg',
  '/images/талреп-якорь.png',
  '/images/термитный заряд.png',
  '/images/трава.png',
  '/images/трава1.png',
  '/images/треугольник.jpg',
  '/images/устаревшие патроны.png',
  '/images/фосфорная граната аирф.png',
  '/images/шеврон беве за ранение.png',
  '/images/штаб бел.jpg',
  '/images/штаб гол.jpg',
  '/images/штаб мин.jpg',
  '/images/штаб1 саперский.png',
  '/images/штаб1.jpg',
  '/images/штурм 1.jpg',
  '/images/штурм 2.jpg'
  
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS);
    })
  );
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});
